### ISSUE TITLE
lab3_2

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/TodorovRV#10]
1) Лучше добавить левые файлы .idea/ в гитигнор.
2) Местами хромает pep8, первое время можете использовать http://pep8online.com/ для валидации кода.
3) Одним из главных моментов задания было использование проектирования "сверху вниз", вы как-то упустили этот момент (поправьте меня, если я ошибаюсь).
4) Переменным и функциям лучше давать какие-то осмысленные имена, без этого сложно понять, как ваш код работает.
5) Пишите комментарии и doc-strings  , код совершенно не читаем
Из плюсов - все работает, это уже хорошо)

**Comment by TodorovRV** [comment]
Разобрал программу, переделал коммиты с нуля. Сама программа была немного переделана для читаемости. В целом все исправлено (наверное).

**Comment by AndreevP** [comment]
В целом все хорошо, но вы все таки исправили не все ошибки по pep8 и в будующем старайтесь избегать каких-то непонятных чисел в коде вроде: 
```
    for i in range(100):
        star = g.Circle(g.Point(500, 500), (r + i))
        star.setFill('orange')
        star.draw(w)
        g.time.sleep(0.00001)
    for j in range(600):
        star = g.Circle(g.Point(500, 500), (r + i + j))
        star.setFill('red')
        star.draw(w)
        g.time.sleep(0.00001)
```

заводите для таких вещей блок констант в начале программы.
Кроме того,  doc-string нужно писать после строки с def (у вас везде до).
