### ISSUE TITLE
lab2/13.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-927/TodorovRV#8]
Оформить отрисовку каждого элемента в отельную функцию для улучшения читаемости кода.

**Comment by TodorovRV** [comment]
Сделано. Плюс один вопрос. Можно ли выставить оценку за первую лабу? А то я уже начинаю волноваться. Вроде и issues все закрыл в срок.

**Comment by kolganovn** [comment]
Первую лабу проверял Антон, поэтому я пока не знаю.
